### ISSUE TITLE
Bungee Support

### ISSUE THREAD

**Issue by Vidsify** [Mitsugaru/PlayerPoints#11]
Is there any way you guys could add bungee support as I really want to set up a network points system. For example is a play buys a pet in lobby for 500 points that gets deducted through out the network. Then if they try to buy a pick in prison for 550 points that can't.

**Comment by Mitsugaru** [comment]
I'm honestly not certain that I'll be able to get around to exploring bungee cord. I haven't kept up with the Minecraft community all that much, not since Bukkit fell apart. I have never worked with bungee cord and it seems to have caused issues with certain setups regarding the point systems they want to create.

**Comment by Vidsify** [comment]
Alright that fair enough. If you can it would be awesome

**Comment by renzotom** [comment]
How about it?
