### ISSUE TITLE
Maven repo down

### ISSUE THREAD

**Issue by Trophonix** [Mitsugaru/PlayerPoints#25]
Your maven repo is down...

**Comment by Mitsugaru** [comment]
Thank you for letting me know. This is because of my server being restarted with the hosting service doing critical maintenance due the Meltdown and Spectre vulnerabilities.

Expect occasional hiccups and downtime while the host continues to do phased system migration and updates until the maintenance is completed.

I will keep an eye on things and try to bring back my services as soon as I can.
